const INPUT_TYPE = {
  ADD_SELECT: "Add Select",
  BALL_TYPE: "Ball Type",
  CHECKBOX: "Checkbox",
  DROPDOWN: "Dropdown",
  REGISTER_CONTACT_INPUT: "Register Contact Input",
  LOCATION_PICKER: "Location Picker",
  SEARCH_BAR: "Search Bar",
  SWITCH: "Switch",
  DATE_PICKER: "date",
  DATE_TIME_PICKER: "Date Time Picker",
  DROPDOWN: "Dropdown",
  LOCATION: "Location",
  NUMBER: "Number",
  OTP_INPUT_BOX: "Otp Input Box",
  PHONE_NO_INPUT_BOX: "Phone Number Box",
  POWER_PLAY: "Power Play",
  SEARCH_BAR: "Search Bar",
  STRING: "String",
  SWITCH: "Switch",
  TIME_PICKER: "time",
};
export default INPUT_TYPE;
